name: Docker Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  save-layers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/checkout@v2
        with:
          repository: kstaken/dockerfile-examples
          path: dockerfile-examples

      - name: Cache docker layers
        uses: ./
        with:
          type: layers
          version: ${{ github.run_id }}

      - name: Build docker images
        run: |
          cd dockerfile-examples/apache
          docker build --tag apache:dev .
          
  restore-layers:
    runs-on: ubuntu-latest
    needs: save-layers-cache
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/checkout@v2
        with:
          repository: kstaken/dockerfile-examples
          path: dockerfile-examples

      - name: Cache docker layers
        uses: ./
        with:
          type: layers
          version: ${{ github.run_id }}

      - name: Build docker images
        run: |
          cd dockerfile-examples/apache
          docker build --tag apache:dev .

  save-buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/checkout@v2
        with:
          repository: kstaken/dockerfile-examples
          path: dockerfile-examples

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Cache Buildx
        uses: ./
        with:
          type: buildx
          path: /tmp/.buildx-cache
          version: ${{ github.run_id }}

      - name: Docker Buildx (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/386 \
            --output "type=image,push=false" \
            --tag apache:dev \
            --file ./dockerfile-examples/apache/Dockerfile \
            ./

  restore-buildx:
    runs-on: ubuntu-latest
    needs: save-buildx-cache
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/checkout@v2
        with:
          repository: kstaken/dockerfile-examples
          path: dockerfile-examples

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Cache Buildx
        uses: ./
        with:
          type: buildx
          path: /tmp/.buildx-cache
          version: ${{ github.run_id }}

      - name: Docker Buildx (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/386 \
            --output "type=image,push=false" \
            --tag apache:dev \
            --file ./dockerfile-examples/apache/Dockerfile \
            ./
