name: Docker Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test-layers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: crazy-max/diun

      - name: Cache docker layers
        uses: dhadka/ezcache@master
        with:
          type: layers
          version: v2

      - name: Build docker images
        run: |
          docker build . --file Dockerfile --tag diun:$(date +%s)

  test-buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: crazy-max/diun

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Cache Buildx
        uses: dhadka/ezcache@master
        with:
          type: buildx
          path: /tmp/.buildx-cache
          version: v2

      - name: Docker Buildx (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/386 \
            --output "type=image,push=false" \
            --tag crazymax/diun:dev \
            --file ./Dockerfile ./
